

import NavBar from "@/components/Navbar";



export const metadata = {
    title: "Main | My App",
    description: "Generated by create next app",
};

export default function MainLayout({ children }) {

    return (
        <>
            <NavBar />
            {children}
        </>
    );
}