export const metadata = {
  title: "Auth | My App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className="min-h-screen bg-slate-900 flex items-center justify-center">
      {children}
    </div>
  );
}